language: python

services:
  - docker

before_install:
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" backend sh deploy/test-entrypoint.sh

after_success: coveralls
