language: python

services:
  - docker

before_install:
  - pip install coveralls
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run backend sh deploy/test-entrypoint.sh

after_success:
  - docker-compose run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" backend coveralls
